version: "3.8"
services:
  streamlit:
    build:
      dockerfile: docker/streamlit/Dockerfile
    volumes:
      - ./app/streamlit-app:/app/app
      - ./data:/app/data
    environment:
      - PREDICTIONS_FILE=${PREDICTIONS_FILE:-/app/data/predictions/predictions.csv}
      - GEO_FILE=${GEO_FILE:-london_boroughs.json}
    ports:
      - "8501:8501"
    command: streamlit run app/london-map-folium.py
