version: "3.8"
services:
  streamlit:
    build:
      context: docker/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./app/streamlit-app:/app/src
      - ./data:/app/data
    environment:
      - PREDICTIONS_FILE=${PREDICTIONS_FILE:-/app/data/predictions/predictions.csv}
    ports:
      - "8501:8501"
    command: streamlit run src/london-map-folium.py
